#!/usr/bin/env bash
# mindwave-pi5-all-in-one.sh
# =============================================================================
# The ENTIRE Raspberry Pi 5 MindWave display setup in one file. No repo
# clone, no separate config.py/service files — this one script writes
# everything it needs and installs itself.
#
# STEP 1 — fill in the two values below:
#   TARGET_USER  -> your Pi username (the one you set in Raspberry Pi Imager)
#   LAPTOP_IP    -> your laptop's local IP address (ipconfig on Windows)
#
# STEP 2 — pick ONE of these two ways to run it:
#
#   (A) Zero-touch, no SSH at all:
#       Right after flashing the SD card with Raspberry Pi Imager (card
#       still plugged into your laptop, not ejected yet), open the boot
#       drive and find firstrun.sh (some Imager versions put it at
#       bootfs/firstrun.sh). Open it in a text editor, and paste this
#       ENTIRE file's contents in, on their own line(s), directly ABOVE
#       the line near the end that looks like:
#           rm -f /boot/firstrun.sh
#       Save, eject, wire the hardware (see WIRING below), insert the
#       card into the Pi, and power on. Give it a few minutes — it needs
#       to download packages before its automatic first reboot. After
#       that, it's running for good, every boot, no SSH ever needed.
#
#   (B) Over SSH, after a normal Imager flash+boot:
#       Copy this file to the Pi (e.g. `scp mindwave-pi5-all-in-one.sh
#       yourpi:~/`), SSH in, then:
#           sudo bash mindwave-pi5-all-in-one.sh
#       Reboot when it finishes: sudo reboot
#
# Either way, on your laptop, run mindwave_pico_bridge.py --link wifi
# exactly as you would for the Pico — this speaks the identical protocol.
#
# WIRING (Raspberry Pi 5, 40-pin header)
# -----------------------------------------------------------------------
# OLED (SSD1306, I2C1):      SDA->GPIO2 (pin 3)  SCL->GPIO3 (pin 5)
#                            VCC->3V3   (pin 1)  GND->GND   (pin 9)
# WS2812B / NeoPixel strip:  DIN->GPIO10/SPI0 MOSI (pin 19), ~330 ohm
#                            resistor in series is good practice.
#                            Use an external 5V supply for more than a
#                            few LEDs (15 LEDs can draw ~900mA) — share
#                            its ground with the Pi's GND. The Pi's own
#                            5V pin (2/4) is fine only for a short strip.
# Buzzer:                    Signal->GPIO17 (pin 11)  GND->GND (pin 14)
#
# NOTE on the LED strip: the Pi 5's RP1 I/O chip broke the traditional
# PWM+DMA method most WS2812B libraries rely on, so this drives it over
# SPI instead (adafruit-circuitpython-neopixel-spi). This is the one
# part that couldn't be tested on real Pi 5 hardware ahead of time — if
# something doesn't work, it's the first place to look.
#
# It's safe to re-run this script — re-running just re-applies the same
# steps and overwrites its own files with the same content.
# =============================================================================

# ── Fill these in ───────────────────────────────────────────────────────
TARGET_USER="pi"            # <-- your Pi username
LAPTOP_IP="192.168.1.100"   # <-- your laptop's local IP address
# ─────────────────────────────────────────────────────────────────────────

LOG_FILE="/boot/mindwave-install.log"
[ -d /boot/firmware ] && LOG_FILE="/boot/firmware/mindwave-install.log"

(
  set -e

  TARGET_HOME="/home/$TARGET_USER"
  INSTALL_DIR="$TARGET_HOME/mindwave-pi5"

  echo "== MindWave Pi 5 all-in-one setup =="
  echo "User: $TARGET_USER   Install dir: $INSTALL_DIR   Laptop IP: $LAPTOP_IP"

  echo "-- Waiting for network --"
  for i in $(seq 1 60); do
    ping -c1 -W2 8.8.8.8 >/dev/null 2>&1 && break
    sleep 2
  done

  echo "-- Enabling I2C and SPI --"
  raspi-config nonint do_i2c 0
  raspi-config nonint do_spi 0

  echo "-- Installing system packages --"
  apt-get update
  apt-get install -y python3-pip python3-venv i2c-tools

  echo "-- Installing Python packages --"
  sudo -u "$TARGET_USER" pip install --break-system-packages \
      luma.oled Pillow adafruit-blinka adafruit-circuitpython-neopixel-spi gpiozero rpi-lgpio

  echo "-- Writing $INSTALL_DIR/main.py --"
  mkdir -p "$INSTALL_DIR"
  cat > "$INSTALL_DIR/main.py" <<'PYEOF'
#!/usr/bin/env python3
"""
main.py — runs on a Raspberry Pi 5, standing in for the Pico
================================================
Connects to mindwave_pico_bridge.py --link wifi (running on your
laptop) over WiFi, and shows the same "A:<attention>,M:<meditation>"
readings on an SSD1306 OLED, color-codes a WS2812B/NeoPixel strip by
blending focus/calm the same way the Pico version does, and buzzes a
buzzer + shows motivational quotes on "Q:<text>" lines.

Uses the exact same wire protocol and handshake as pico/main.py's WiFi
mode, so mindwave_pico_bridge.py needs NO changes to talk to this
instead of a Pico — just run it with --link wifi as usual.

Generated by mindwave-pi5-all-in-one.sh — LAPTOP_HOST below was filled
in from that script's LAPTOP_IP setting.
"""

import socket
import time

# ── Config ────────────────────────────────────────────────────────────────────
LAPTOP_HOST  = "LAPTOP_IP_PLACEHOLDER"
LAPTOP_PORT  = 5005    # must match mindwave_pico_bridge.py's --wifi-port (default 5005)
NUM_LEDS     = 15     # how many LEDs are on the strip — match pico/main.py's value
BUZZER_PIN   = 17
BUZZ_S       = 0.2    # how long the buzzer sounds for
QUOTE_DISPLAY_S = 10.0  # how long a motivational quote stays on screen
OLED_I2C_ADDR = None   # None = auto-detect (tries 0x3C then 0x3D)
OLED_WIDTH   = 128
OLED_HEIGHT  = 32
DATA_TIMEOUT_S = 5.0   # seconds without a line before we show "no signal"
BRIGHTNESS   = 0.35    # 0..1, keeps the strip comfortable to look at
HANDSHAKE    = b"MWHELLO"
# ──────────────────────────────────────────────────────────────────────────────


# ── OLED (SSD1306 over I2C, via luma.oled) ────────────────────────────────────
def init_oled():
    """Bring up the OLED. Returns None (instead of crashing) if it can't be
    found — or if the luma packages aren't even installed — so the LED
    strip/buzzer still work while OLED wiring/setup is debugged."""
    try:
        from luma.core.interface.serial import i2c
        from luma.core.error import DeviceNotFoundError
        from luma.oled.device import ssd1306
    except ImportError as e:
        print(f"OLED libraries not installed ({e}) — continuing without it. "
              f"pip install luma.oled Pillow")
        return None

    addrs_to_try = [OLED_I2C_ADDR] if OLED_I2C_ADDR else [0x3C, 0x3D]
    for addr in addrs_to_try:
        try:
            serial = i2c(port=1, address=addr)
            device = ssd1306(serial, width=OLED_WIDTH, height=OLED_HEIGHT)
            print(f"OLED found at {hex(addr)}")
            return device
        except DeviceNotFoundError:
            continue
        except Exception as e:
            print(f"OLED found at {hex(addr)} but failed to initialize: {e}")
            return None
    print("No SSD1306 responded on I2C1 — check wiring: SDA=GPIO2, SCL=GPIO3, "
          "VCC=3V3, GND=GND, and that I2C is enabled (raspi-config).")
    return None


oled = init_oled()


def oled_lines(*lines):
    """Clear and draw up to 4 lines of text (8px each, matches the Pico's
    16-char/4-line layout closely enough for the same short strings)."""
    if not oled:
        return
    from luma.core.render import canvas
    with canvas(oled) as draw:
        for i, line in enumerate(lines[:4]):
            draw.text((0, i * 8), line, fill="white")


# ── LED strip (WS2812B over SPI) ──────────────────────────────────────────────
def init_strip():
    try:
        import board
        import busio
        import neopixel_spi as neopixel
        spi = busio.SPI(board.SCK, MOSI=board.MOSI)
        pixels = neopixel.NeoPixel_SPI(spi, NUM_LEDS, pixel_order=neopixel.GRB, auto_write=False)
        print("LED strip initialized over SPI")
        return pixels
    except Exception as e:
        print(f"LED strip init failed ({e}) — continuing without it.")
        return None


strip = init_strip()


def set_strip_color(rgb):
    if not strip:
        return
    strip.fill(rgb)
    strip.show()


def set_strip_idle():
    set_strip_color((0, 0, 20))  # dim blue = idle/no data yet


# ── Buzzer ─────────────────────────────────────────────────────────────────────
def init_buzzer():
    try:
        from gpiozero import DigitalOutputDevice
        return DigitalOutputDevice(BUZZER_PIN)
    except Exception as e:
        print(f"Buzzer init failed ({e}) — continuing without it.")
        return None


buzzer = init_buzzer()


def buzz():
    if not buzzer:
        return
    buzzer.on()
    time.sleep(BUZZ_S)
    buzzer.off()


# ── Display helpers (mirrors pico/main.py's show_reading/show_quote/show_waiting) ─
def focus_color(attention, meditation):
    """Green = focused (attention), red = calm (meditation), blended
    when both are present, scaled by BRIGHTNESS."""
    attention = max(0, min(100, attention))
    meditation = max(0, min(100, meditation))
    r = int(255 * meditation / 100 * BRIGHTNESS)
    g = int(255 * attention / 100 * BRIGHTNESS)
    return (r, g, 0)


def show_reading(attention, meditation):
    oled_lines(f"Focus: {attention}", f"Calm:  {meditation}")
    set_strip_color(focus_color(attention, meditation))


def wrap_text(text, width=20, max_lines=4):
    """Word-wrap text for the OLED. Pi 5's default PIL font is a little
    narrower than the Pico's fixed 8px font, so 20 chars/line fits."""
    words = text.split(" ")
    lines, cur = [], ""
    for w in words:
        candidate = (cur + " " + w).strip()
        if len(candidate) <= width:
            cur = candidate
        else:
            if cur:
                lines.append(cur)
            cur = w[:width]
        if len(lines) >= max_lines:
            break
    if cur and len(lines) < max_lines:
        lines.append(cur)
    return lines[:max_lines]


def show_quote(text):
    oled_lines(*wrap_text(text))
    buzz()
    time.sleep(max(0.0, QUOTE_DISPLAY_S - BUZZ_S))


def show_waiting(msg):
    oled_lines("MindWave", msg)
    set_strip_idle()


def parse_line(line):
    """Expects "A:65,M:42" — returns (attention, meditation) or None."""
    attention = meditation = None
    for part in line.strip().split(","):
        if part.startswith("A:"):
            attention = int(part[2:])
        elif part.startswith("M:"):
            meditation = int(part[2:])
    if attention is None or meditation is None:
        return None
    return attention, meditation


# ── Link: connects to mindwave_pico_bridge.py --link wifi, same protocol ─────
def connect_to_laptop():
    """Open a TCP connection to the laptop AND verify it's actually
    mindwave_pico_bridge.py with the same handshake pico/main.py uses."""
    attempt = 0
    while True:
        attempt += 1
        show_waiting(f"link {attempt}")
        s = None
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.settimeout(5)
            s.connect((LAPTOP_HOST, LAPTOP_PORT))
            s.sendall(HANDSHAKE)
            reply = s.recv(16)
            if reply != HANDSHAKE:
                raise OSError(f"bad handshake reply: {reply!r}")
            s.settimeout(None)
            print(f"Connected to laptop at {LAPTOP_HOST}")
            return s
        except OSError as e:
            print(f"Couldn't reach the laptop: {e} — retrying in 3s...")
            if s is not None:
                try:
                    s.close()
                except Exception:
                    pass
            time.sleep(3)


def read_available_lines(link_sock, rx_buf):
    """Return (lines, updated_rx_buf, updated_link_sock). A recv() timeout
    just means nothing arrived in this ~500ms tick — perfectly normal, same
    as poll(500) returning nothing on the Pico — and must NOT be treated as
    a lost connection; only a real error or the peer cleanly closing
    (recv() returning b"") means we should reconnect."""
    try:
        data = link_sock.recv(256)
    except socket.timeout:
        return [], rx_buf, link_sock
    except OSError:
        data = None

    if not data:
        print("Lost connection to laptop — reconnecting...")
        try:
            link_sock.close()
        except Exception:
            pass
        new_sock = connect_to_laptop()
        new_sock.settimeout(0.5)
        return [], b"", new_sock

    rx_buf += data
    lines = []
    while b"\n" in rx_buf:
        raw, rx_buf = rx_buf.split(b"\n", 1)
        lines.append(raw.decode("utf-8", "ignore"))
    return lines, rx_buf, link_sock


def main():
    show_waiting("connecting...")
    link_sock = connect_to_laptop()
    link_sock.settimeout(0.5)  # so recv() doubles as our idle tick, like poll(500) on the Pico

    show_waiting("waiting...")
    rx_buf = b""
    last_data = time.monotonic()
    showing_no_signal = False

    while True:
        lines, rx_buf, link_sock = read_available_lines(link_sock, rx_buf)

        for line in lines:
            if line.startswith("Q:"):
                show_quote(line[2:].strip())
                last_data = time.monotonic()
                showing_no_signal = False
            else:
                parsed = parse_line(line)
                if parsed:
                    last_data = time.monotonic()
                    showing_no_signal = False
                    show_reading(*parsed)

        if not showing_no_signal and time.monotonic() - last_data > DATA_TIMEOUT_S:
            showing_no_signal = True
            show_waiting("no signal")


if __name__ == "__main__":
    main()
PYEOF

  sed -i "s/LAPTOP_IP_PLACEHOLDER/$LAPTOP_IP/" "$INSTALL_DIR/main.py"
  chown -R "$TARGET_USER:$TARGET_USER" "$INSTALL_DIR"

  echo "-- Installing the auto-start service --"
  cat > /etc/systemd/system/mindwave-pi5.service <<EOF
[Unit]
Description=MindWave Pi 5 display (OLED + LED strip + buzzer)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 $INSTALL_DIR/main.py
WorkingDirectory=$INSTALL_DIR
User=$TARGET_USER
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable --now mindwave-pi5.service

  echo "== Done =="
  echo "Check it's running:   sudo systemctl status mindwave-pi5.service"
  echo "Watch live output:    journalctl -u mindwave-pi5.service -f"
) > "$LOG_FILE" 2>&1 || echo "MindWave install hit an error — see $LOG_FILE"
